### ISSUE TITLE
Not working in opera

### ISSUE THREAD

**Issue by gchokhonelidze** [greena13/react-hotkeys#107]
in opera only Space is called, but keys like (A,S,D,F) not being called.

**Comment by greena13** [comment]
Thanks for reporting, gchokhonelidze.

Are you pressing these keys in sequence (one after another), in a combination (at the same time) or separately?

**Comment by gchokhonelidze** [comment]
Hello greena13,
I am pressing separately, after checking I found out that it sometimes not works, and sometimes works. I cannot find out why it happens.

**Comment by greena13** [comment]
Are you able to confirm the same keys work in another browser?

**Comment by gchokhonelidze** [comment]
Yes no issues in other browsers

**Comment by greena13** [comment]
What versions of `react-hotkeys` and Opera are you using? How are you setting up the the keymaps and handlers?

I just tested on Opera v54.0.2952.54 (Mac version) using `react-hotkeys` `v1.1.4` and keyboard shortcuts appear to be working correctly.

**Comment by greena13** [comment]
Closing as inactive. Please comment if you'd like to resume debugging.
