### ISSUE TITLE
Fixed demo, new link

### ISSUE THREAD

**Issue by jacaetevha** [greena13/react-hotkeys#108]
`this.changeColor` resulted in `undefined` because `changeColor` was defined after the `hotKeyHandlers` in `HOCWrappedNode`. https://codesandbox.io/s/x73mw4knlo updates the code so that `changeColor` is defined first and available in the scope of `hotKeyHandlers`. Pressing `ALT+C` on the HOC node now works.

**Comment by greena13** [comment]
Thanks, jacaetevha! Would you be able to create a PR that replaces the link in the Readme with this one?

**Comment by jacaetevha** [comment]
Done #109
