### ISSUE TITLE
Failure to use react-hotkeys

### ISSUE THREAD

**Issue by cbarraford** [greena13/react-hotkeys#110]
When trying to use react-hotkeys, I run into an error when loading the HotKeys into `render`.

```
<HotKeys keyMap={keyMap} handlers={handlers}>
</HotKeys>
```

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AchievementDeck`.
```

Am I seeing this because I'm using react 15?

**Comment by greena13** [comment]
Hey cbarraford, sorry to hear that you are having issues.

I am not really sure at this point why you may be experiencing this particular issue.

Could you please let me know how define your component `AchievementDeck`? I'm interested in how you import React and possibly `Component` if you use it, and how you define the component. The `render` method may also be helpful.

Thanks.

**Comment by cbarraford** [comment]
Here is some more info, hope this helps....

```
import HotKeys from 'react-hotkeys'

export default class AchievementDeck extends React.Component {

  ......

  render() {

    const keyMap = {
      openAchievementModal: 'c',
    }

    const handlers = {
      'openAchievementModal': () => {
        console.log("Opening achievement...");
        this.open()
      }
    }

    return (
      <div className="row">
        <HotKeys keyMap={keyMap} handlers={handlers} focused>
              .....
        </HotKeys>
     </div>
}
```

**Comment by greena13** [comment]
This may be because you are using React 15 as you suggested. I assume if you do the following, it comes out as undefined:

```
import React, { Component } from 'react';

console.log(Component) // undefined?
```

If so, I'd say we have found our culprit. Please confirm and in the meantime I'll try and come up with a suggested way forwards.

**Comment by cbarraford** [comment]
@greena13 i can log Component ok using the code you have above

```
Component: ƒ ReactComponent(props, context, updater) {
  this.props = props;
  this.context = context;
  this.refs = emptyObject;
  // We initialize the default updater but the real one gets injected by the
  // …
```

What is the recommended version of React? v16?

**Comment by cbarraford** [comment]
I figured out the problem, its because I need the `{}` on the import. I don't fully understand why that is, and why on other packages i don't need the curly brackets and why I do need them here. 

From 
```
import HotKeys from 'react-hotkeys'
```

To
```
import { HotKeys } from 'react-hotkeys'
```

**Comment by cbarraford** [comment]
maybe es6 related?

**Comment by greena13** [comment]
Ah, yes. Sorry, I should have picked that up. React hotkeys doesn't have a single default export, it exports a number of things - one of them being the HotKeys component. That's why you have to use this syntax.

Babel's ES6 article has a pretty good explanation of ES6 module exports - that's probably a good place to start.
