### ISSUE TITLE
Hotkeys not working on dynamic KeyMap assigning

### ISSUE THREAD

**Issue by mangeshlokhande** [greena13/react-hotkeys#111]
whenever i try to assign a combination of keys into keymap dynamically , key listening is not taking place at that time. Listening is working only after a refresh/reload has been done at least once.

**Comment by greena13** [comment]
Hey mangeshlokhande, could you possible share some code to illustrate exactly what you're doing?

**Comment by greena13** [comment]
Closing as inactive for now.
