### ISSUE TITLE
command+option+n is not working in chrome

### ISSUE THREAD

**Issue by artem713** [greena13/react-hotkeys#115]
According to this doc https://support.google.com/chrome/answer/157179?hl=en, `command+option+n` is not a browser specific shortcut, but for some reason, this combination is not working.

**Comment by greena13** [comment]
Hey artem713, 

How are you setting up the key map (code, please)? 

Does it work in other browsers?

**Comment by artem713** [comment]
Hey @greena13,

I was using your example for checking this. I've also tried it on the Safari with no luck. https://codesandbox.io/s/w756l57yr5

Regards,
Artem

**Comment by artem713** [comment]
@greena13 I've checked it again in the Chrome Version 70.0.3538.102 (Official Build) (64-bit), it's not working for me.

1. yes, I'm clicking on a square before pressing `command+alt+n` or `command+option+n`
2. yes, `alt+up` is working fine
3. yes
4. I'm using Mac

**Comment by greena13** [comment]
It represents quite a significant upgrade, but I have just finished fixing a lot of issues to do with combinations involving Cmd in [v2.0.0-pre4](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre4). If you have the time to upgrade, I would suggest this is your best bet for resolving your reported issue as unfortunately no further development is planned on v1.*

If you have any questions or would like any additional support, just let me know.
