### ISSUE TITLE
how to turn off hotkeys on <input/> focus when typing

### ISSUE THREAD

**Issue by chancesmith** [greena13/react-hotkeys#116]
When this gets fired...
```javascript
const keyHandlers = {
      focusInput: () => {
        document.querySelector('input').focus();
        return false;
     },
}
```

How can I keep HotKeys from firing as I type in the focused input field?

We're checking to see if there is something built-in before we find a workaround.

**Comment by barrettg** [comment]
You could track the if the input has focus and then simply return in your handler functions.  See this: https://codesandbox.io/s/18mppo62kj

**Comment by chancesmith** [comment]
Yeah, @barrettg! That works. 😎
