### ISSUE TITLE
export all typescipt types

### ISSUE THREAD

**Issue by Bearsie** [greena13/react-hotkeys#120]
Could you please consider exporting all of your typescript types and interfaces?

**Comment by greena13** [comment]
Hey @Bearsie, could you please clarify what you meant by exporting the Typescript types and interfaces? There is an [index.d.ts](https://github.com/greena13/react-hotkeys/blob/master/index.d.ts) file included in the project.

**Comment by greena13** [comment]
Thanks for clarifying. My understanding was that index.d.ts was supposed to describe only the public exports of the module. But I can see a use case for wanting to reuse some of the types in your own code.

**Comment by greena13** [comment]
This will be included as part of [v2.0.0-pre1](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre1) when it's released soon.
