### ISSUE TITLE
Sequence containing same keys

### ISSUE THREAD

**Issue by bginsburg** [greena13/react-hotkeys#123]
Hey i have a use case of which we have a hotKey sequence of `ctrl+alt+a` and a sequence of `ctrl+alt+a+b`
Because both have the same three keys i'm not sure the `ctrl+alt+a+b` handler will ever be called.
Does this library support this use case?

**Comment by greena13** [comment]
Hi bginsburg, my understanding is that yes, indeed the longer combination can be matched, but if you use only the string syntax you mentioned, the shorter will always be matched on the way to getting to the longer one.

I suggest you use the object syntax for defining actions to bind the shorter sequence to keyup and the longer one to keydown or keypress. That way, you should get the desired behaviour of only calling one of the actions associated with the sequences.
