### ISSUE TITLE
Pass handlers to withHotKeys

### ISSUE THREAD

**Issue by Floriferous** [greena13/react-hotkeys#127]
I love HOCs, and I believe it would be amazing if picking up this library was as simple as doing this:

```js
const App = props => <MyFullApp />

// Magic, without changing anything but this line in my entire massive code base,
// space bar suddenly triggers something :)
export default withHotKeys({ handlers: { space: () => console.log('it works!') }, global: true })(App);
```

Or even pass it as the second argument, in the `componentProps` of the HOC, but that does not seem to work (Am I doing something wrong?).

To be honest, I think that the API of the HOC is bad, since both arguments are passed down to `<HotKeys />`, in my opinion, it should simply be `withHotKeys( componentProps: Object )` to which you can pass all the props you want, _including_ `handlers`. Sadly, this would be a breaking change, but I believe simpler, and better design.

Also, `global` would be a shortcut for `focused: true, attach: window`, which I had to dig for in the issues to find out.

**Comment by greena13** [comment]
Thanks for your feedback, Floriferous.

The new [withHotKeys HoC API](https://github.com/greena13/react-hotkeys/tree/2.0.0-pre1#withhotkeys-hoc-api) in [https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre](v2.0.0-pre) looks a lot more like you described. It will be released soon.
