### ISSUE TITLE
Warnings in react-hotkeys when using React's strict mode

### ISSUE THREAD

**Issue by edmorley** [greena13/react-hotkeys#128]
Hi!

React 16.3 added a new strict mode, which highlights potential issues in an app (such as those that will cause problems when using the upcoming async mode):
https://reactjs.org/docs/strict-mode.html

Enabling it for our app resulted in several errors coming from `react-hotkeys`:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at job-view/index.jsx:28)

componentWillMount: Please update the following components to use componentDidMount instead: 
HotKeys
```

-> see: https://reactjs.org/docs/strict-mode.html#identifying-unsafe-lifecycles

```
Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode (at job-view/index.jsx:28)

Please update the following components: HotKeys
```

-> see: https://reactjs.org/docs/strict-mode.html#detecting-legacy-context-api

```
Warning: findDOMNode is deprecated in StrictMode.
findDOMNode was passed an instance of HotKeys which is inside StrictMode.
Instead, add a ref directly to the element you want to reference.

    in div (created by FocusTrap)
    in FocusTrap (created by HotKeys)
    ...
```

-> see: https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

Many thanks :-)

**Comment by greena13** [comment]
This will be fixed in [https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre](v2.0.0-pre) when it's released.

**Comment by edmorley** [comment]
Many thanks!

**Comment by ndelangen** [comment]
I'm using v2.0.0-pre4

I'm still getting this warning:

```
vendors~main.64d108ae760cbd63d1ea.bundle.js:138014 Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode

Please update the following components: GlobalHotKeys

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by greena13** [comment]
Hi @ndelangen, thanks for making me aware. I have [created a separate issue](https://github.com/greena13/react-hotkeys/issues/151) to track this.
