### ISSUE TITLE
Seeking new package maintainers

### ISSUE THREAD

**Issue by greena13** [greena13/react-hotkeys#130]
It has become increasingly and painfully apparent that I do not currently have the time to dedicate to react-hotkeys that it currently needs. And so it is time to ask for a little help or - if people are willing - to hand off react-hotkeys to the next custodian(s).

# Project direction

I have been trying to refactor react-hotkeys to no longer use mousetrap (a library that appears to no longer be maintained) and to better integrate with React, using its own event delegation where possible, and to optimise its performance. 

It has unfortunately come at the expense of maintaining the library as it currently exists, with a number of mounting issues stacking up that I have been reluctant to address because I know the refactor will fix or obviate them completely. It has also created friction for adding new features, as they move the target the refactor must hit further away, as I try to get the code back to a point where it supported all use-cases and functionality of the latest release.

I still believe this is the future of the package; I have yet to encounter any problems with the refactor, other than my lack of time to dedicate to it and have observed it working as I expected. However, I have growing concerns that the users of this package deserve a maintainer that will continue to address the issues they are experiencing with react-hotkeys now. Perhaps the refactor is best released as a separate package that users will be able to migrate to if they so choose in the future.

This refactor more or less implements the same API as the current version of the package, with a few improvements. It's located on the `dev_remove_mousetrap` branch.

In the meantime, I suggest any new maintainers direct their attention to the plethora of outstanding issues and pull requests.

If you are interested in helping out, please let me know here and we can begin to discuss next steps.

**Comment by greena13** [comment]
A month onwards, I was able to carve out the time to get this library where I think it needed to be. It's not perfect, but it's much better than the stagnated state it was left in.

I would still really appreciate additional maintainers and support from the community in raising issues, creating PRs and suggesting additional features. Going forward, I will have limited time to dedicate to this library so my role will largely be relegated to an administerial one (reviewing issues and PRs, providing guidance and documentation amendments, etc).

**Comment by greena13** [comment]
Thanks rgbkrk, that sounds fantastic. 

I would love to hear how it's working for your use case and work with you on any issues.

**Comment by greena13** [comment]
rgbkrk, I noticed you forked a few days ago. Just wanted to let you know there's been a new [sizable update](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre4).

**Comment by natew** [comment]
Just wanted to chime in with some thanks. While I can't really help much at the moment, this is the only really viable shortcut library in React, and looks like the new version really improves it quite a bit. Going to be testing v2 today, and really appreciate your work here.

**Comment by greena13** [comment]
Thanks, @natew. I am still trying to find the time to get this major release over the line - you're encouragement is appreciated.

**Comment by natew** [comment]
Thank you! On the code-side, one thing I'm noticing is installing from "source" (github sha in package.json), seems the types get messed up. I tried doing this because `pre4` doesn't have the configure type set up and wanted to patch it quickly, but if you do from github directly it does this:

```
node_modules/react-hotkeys/index.d.ts:84:15 - error TS2694: Namespace 'React' has no exported member 'forwardRef'.

84   ref?: React.forwardRef<React.ComponentClass, ComponentPropsBase>
```

Perhaps needs a postinstall step to build or something like that?

**Comment by greena13** [comment]
Thanks for reporting, @natew. I've created a [separate issue](#128) to track this. (The TS definitions have been the bane of my life maintaining this package as I do not use them directly, myself.)

If you have the time to dig into this and perhaps create a PR, it would be greatly appreciated; otherwise I will try and get to it in due time.

**Comment by StephenHaney** [comment]
Hey Aleck,

Thanks for all you're doing here! We love this library.

We're eagerly waiting the next release. We have some bug fixes that you've already committed to master. Do you have an idea on the timing for the next publish?

On another note, we'd love to make a contribution for the time you're putting into this. Do you have an open collective or similar account?

Cheers!

**Comment by greena13** [comment]
@StephenHaney, you are very kind. I don't currently have a method of accepting financial support, but you have given me the push to start setting one up this weekend. I will let you know the details shortly, when it is ready. 

Apologies regarding the pending bugfixes. This has been a source of growing anxiety for me - I am aware that there are resolved issues that have not yet been released, but I keep trying to sneak "one more fix" in before life unexpectedly interrupts and delays it further. I will try and draw a line and get the next pre-release out in the next couple of days. Apologies again for any delays this may be causing you (and others).

**Comment by greena13** [comment]
@StephenHaney, I've just published [v2.0.0-pre5](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre5). I hope it resolves some of the issues you are experiencing.

Stay tuned for ways to support the project.

**Comment by StephenHaney** [comment]
Great news! Thanks for pushing it out. We'll continue to follow along, support, and contribute.

**Comment by greena13** [comment]
@StephenHaney, I've just added a [Support section to the Readme](https://github.com/greena13/react-hotkeys#support). This is my first time setting up such a system for an OS project, so I am drawing heavily from other projects I'm aware of. I hope you find a method of support that you feel comfortable with.

Let me know if you have any questions/concerns.

**Comment by StephenHaney** [comment]
That's awesome @greena13! We'll send something your way shortly. Thanks again for all you do on this project.

**Comment by greena13** [comment]
Thanks! The fact you asked how you could support the project and followed through is greatly appreciated.

**Comment by greena13** [comment]
I'm closing this issue for now, as a few months on, I have managed to carve out the time to continue working on this repo. I would, however, continue to encourage those who are interested and able to make suggestions and contributions to help support the library and its continued development. It's much appreciated.
