### ISSUE TITLE
Including react keys in testable components

### ISSUE THREAD

**Issue by MurrayJack** [greena13/react-hotkeys#131]
Hi

I am using hotkeys in a component i am trying to develop and one of the use cases is that it is keyboard accessible.  

Everything works perfectly when im running this, but the issue comes when u try to test it.....

`
const Header = ({ Mode, Value, Placeholder, OnValueClear, OnCloseClick, OnOpenClick }) => {
  const handlers = {
    'esc': OnCloseClick,
    'down': OnOpenClick,
    'up': OnCloseClick,
    'enter': OnOpenClick,
    'space': OnOpenClick,
  }
  
  return (
    <HotKeys 
      handlers={handlers} 
      onClick={OnOpenClick} 
      tabIndex={0}>
      
      <snd.Header>Super Header</snd.Header>
    </HotKeys>
  );
};`

and i am trying to test this using jest and enzyme, with the following code

`
const control = enzyme.mount(<SearchableNestedDropdown {...props} />);
control.find("Header").simulate("keypress",  { keyCode: 40, which: 40, key: "down" });
`

but nothing happens :(

ive tried this

`const event = new Event('keypress');
      event.keyCode = 40;
      event.which = 40;
      event.key = 'down';
      event.bubbles = true;

      control.find("Header").getDOMNode().dispatchEvent(event);`

but that doesnt seem to work either, really want this component to be testable the rest of it works super cool,  :)

Ill fork a copy and have a look at the code in the mean time 

thanks all whom read this!
Murray

**Comment by greena13** [comment]
Hi Murray,

My best guess for the issue you are seeing is that you are not simulating the key event on a DOM-mountable component (e.g. div, span, input, etc) so it's not actually being picked up by any listeners.

Are you able to change the call to `find()` to return such an element and report back whether you got any different results?

**Comment by MurrayJack** [comment]
after rereading my post, ill create a CodeSanbox for the issue might make it easier

**Comment by greena13** [comment]
If possible, I'd suggest you upgrade to the latest pre-release (currently pre-2) and try again:

```
yarn upgrade react-hotkeys@next
```

The pre-release represents a major rewrite of the internals (and some of the API). It works natively with React, so using `enzyme`'s `simulate` method will work just fine (most of `react-hotkeys`'s own test suite is written using it).

**Comment by greena13** [comment]
I'm closing this for now. Please let me know if this is still an issue for you, using the new pre-release version of the package.
