### ISSUE TITLE
Documentation describe unexistent GlobalHotKeys component

### ISSUE THREAD

**Issue by achekulaev** [greena13/react-hotkeys#134]
GlobalHotKeys component import and usage is not explained in README.md and is not working.

```javascript
import {GlobalHotKeys} from 'react-hotkeys';
...
<GlobalHotKeys {props} />
```

is not working. At the same time approach described in https://github.com/greena13/react-hotkeys/issues/12#issuecomment-128278693 works fine as a replacement

**Comment by evanc** [comment]
the documentation shown is for a pre-release version, if you install `v2.0.0-pre2` GlobalHotKeys will be available.

Here's the stable version documentation:
https://github.com/greena13/react-hotkeys/tree/v1.1.4

**Comment by greena13** [comment]
Hey achekulaev, apologies that you missed the notification at the top of the readme about documentation version.  I have added some extra emphasis to try and make it more obvious to future readers.

Thanks for helping out and answering this question, evanc. I appreciate the helping hand!

**Comment by achekulaev** [comment]
@evanc @greena13 oh right, I forgot to look what branch the docs are for. Thanks!
