### ISSUE TITLE
I think it is annoying to have key map and handlers separated, why not make them together in simple for model form submit?

### ISSUE THREAD

**Issue by dotku** [greena13/react-hotkeys#140]
I think a better structure might be: 

```
 hotkeyHandlers = {
  submit: {
    keyMap: ['enter'],
    handler: () => { ... }
  }
 }
```

**Comment by greena13** [comment]
Hi dotku,

Thanks for taking the time to make a suggestion. The reason they are separated is to accommodate for  larger applications, with many levels of hotkeys and to follow good software design principles of separating the interface specification and implementation definition.

Defining them separately allows you to define your actions once (using the `keyMap` prop), higher up in the application and specify how those actions are handled (using the `handlers` prop), depending on what component is in focus.

It also provides a single place in your code for you to add or remove extra key combinations that trigger the same action.

I do have plans to explain best practices for using `react-hotkeys` in the future, once the pre-release is ready. However, for now it's safe to say the separation of defining the keys that trigger actions and how those actions are handled are central to the power of the library.

If you have a really simple application, are determined to define both your key maps and your handlers as succinctly as possible, and don't mind using a feature that is considered deprecated and may be removed in future versions, you can check out [Hard Sequence Handlers](https://github.com/greena13/react-hotkeys#deprecated-hard-sequence-handlers).
