### ISSUE TITLE
[BUG] Delete key is not detected 

### ISSUE THREAD

**Issue by snaumov** [greena13/react-hotkeys#145]
**Describe the bug**

Delete key is not registered (2.0.0-pre.4 version)

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**

Hotkeys

**Expected behavior**

on delete key pressed, the function should be called

**Platform (please complete the following information):**
 - Version of react-hotkeys
2.0.0-pre.4
Chrome
Ubuntu 18.10

**Are you willing and able to create a PR request to fix this issue?**
Yes

**APPLICABLE TO v2.0.0-pre1 AND ABOVE: ======================**

**Include the smallest log that includes your issue:**

Set logging to verbose (you'll need the development build if its possible):

```
import { configure } from 'react-hotkeys';

configure({
  logLevel: 'verbose'
})
```

**What Configuration options are you using?**
none

```
configure({
  //options
})
```

Codesandbox repro:
https://codesandbox.io/s/wy5qk62528

**Comment by snaumov** [comment]
console output

HotKeys (F3📙-C0🔺-P0🔺:) Focused. 

index.js:26 HotKeys (F3📙-C0🔺-P0🔺:) Component options:
 {
    "actions": {
        "delete": [
            {
                "prefix": "",
                "actionName": "delete",
                "sequenceLength": 1,
                "id": "Backspace",
                "keyDictionary": {
                    "Backspace": true
                },
                "eventBitmapIndex": 0,
                "size": 1
            },
            {
                "prefix": "",
                "actionName": "delete",
                "sequenceLength": 1,
                "id": "Backspace",
                "keyDictionary": {
                    "Backspace": true
                },
                "eventBitmapIndex": 0,
                "size": 1
            }
        ]
    },
    "handlers": {
        "delete": "function _delete() {\n        return _this.handleDelete();\n      }"
    },
    "componentId": 0,
    "options": {
        "defaultKeyEvent": "keydown"
    }
}
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) New 'Delete' keydown event.
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) Started a new combination with 'Delete'.
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) Key history: [
    {
        "keys": {
            "Delete": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Delete": [
                [
                    false,
                    false,
                    false
                ],
                [
                    true,
                    false,
                    false
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    }
].
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) Attempting to find action matching 'Delete' keydown . . .
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) Internal key mapping:
 {
    "sequences": {
        "": {
            "combinations": {
                "Backspace": {
                    "prefix": "",
                    "sequenceLength": 1,
                    "id": "Backspace",
                    "keyDictionary": {
                        "Backspace": true
                    },
                    "size": 1,
                    "events": {
                        "0": {
                            "actionName": "delete",
                            "eventBitmapIndex": 0,
                            "handler": "function _delete() {\n        return _this.handleDelete();\n      }"
                        }
                    }
                }
            }
        }
    },
    "eventBitmap": [
        true,
        false,
        false
    ],
    "longestSequence": 1
}
index.js:26 HotKeys (F3📙-E20💙-C0🔺-P0🔺:) No matching actions found for 'Delete' keydown.
index.js:26 HotKeys (F3📙-E21💛-C0🔺-P0🔺:) New 'Delete' keypress event.
index.js:26 HotKeys (F3📙-E21💛-C0🔺-P0🔺:) Key history: [
    {
        "keys": {
            "Delete": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Delete": [
                [
                    true,
                    false,
                    false
                ],
                [
                    true,
                    true,
                    false
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    }
].
index.js:26 HotKeys (F3📙-E21💛-C0🔺-P0🔺:) Ignored 'Delete' keypress because it doesn't have any keypress handlers.
index.js:26 HotKeys (F3📙-E22💜-C0🔺-P0🔺:) New 'Delete' keyup event.
index.js:26 HotKeys (F3📙-E22💜-C0🔺-P0🔺:) Key history: [
    {
        "keys": {
            "Delete": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    },
    {
        "keys": {
            "Delete": [
                [
                    true,
                    true,
                    false
                ],
                [
                    true,
                    true,
                    true
                ]
            ]
        },
        "ids": [
            "Delete"
        ],
        "keyAliases": {}
    }
].
index.js:26 HotKeys (F3📙-E22💜-C0🔺-P0🔺:) Ignored 'Delete' keyup because it doesn't have any keyup handlers.
index.js:26 HotKeys (F3📙-C0🔺-P0🔺:) Lost focus.

**Comment by snaumov** [comment]
Turns out I should be using Browser key events: `Delete` instead of `del`, as on version 1.x

**Comment by greena13** [comment]
Thanks for reporting, snaumov. 

This is indeed a bug. `del` should work in the latest pre-release. I've crafted a fix that should go out with the next release.

**Comment by wulucxy** [comment]
still not work，first `cmd + c`，then `[del , backspace]` not work

**Comment by wulucxy** [comment]
@greena13 is [`del`, 'backspace'] only work on `GlobalHotKeys`?

**Comment by FrantisekVrab** [comment]
> 
> 
> still not work，first `cmd + c`，then `[del , backspace]` not work

i think this could be due to some "focus" issues... e.g. like you have loose focus on elements which should listen to these shortcuts..

**Comment by dwilt** [comment]
I'm also having trouble with delete as well.. tried `del`, `Delete`, and `delete`.. if I replace it with any other shortcut like `command+g` or `enter`, the callback gets fired..
