### ISSUE TITLE
[BUG] keybinding is not working when attach={window} inside input focus

### ISSUE THREAD

**Issue by rajnishcoder** [greena13/react-hotkeys#146]
**Describe the bug**
Hi, It was working fine in reactjs project outside and inside input focus, then I need to add focus to window so i did `<HotKeys focused={true} attach={window} handlers={this.handlers}>` my keymap is on the main container `keyMap={this.keyMap}` and it is stop working only when the focus inside any input element. outside input focus it is still working fine.

If I remove `attach={window} ` it working fine but i need focus on window

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
I'm using `<HotKeys>` as code above.

**Expected behavior**
It should work inside and outside input focus.

**Platform (please complete the following information):**
 - Version of react-hotkeys:- `"react-hotkeys": "^1.1.4"`
 - Browser:- chrome
 - OS: Linux (fedora)

**Comment by greena13** [comment]
Hello @rajnishcoder,

Thanks for filing your issue. You have unfortunately triggered some unclear and implicit behaviour that is baked into mousetrap by binding to `window`. [This comment](https://github.com/greena13/react-hotkeys/issues/100#issuecomment-382297439) explains it in detail, but in brief mousetrap ignores key event from `input` tags, when bound to window.

I suggest you follow the advice in the linked comment, or if you are just starting your integration with `react-hotkeys` (or are willing to spend some time reading through the [upgrade notes](https://github.com/greena13/react-hotkeys/releases) and testing) upgrade to the latest pre-release to avoid this issue.

Please let me know if you have any more questions, but I am closing for now.

**Comment by rajnishcoder** [comment]
@greena13 thanks for the reply and the solution that works :100:
