### ISSUE TITLE
Support for Functional Components?

### ISSUE THREAD

**Issue by StephenHaney** [greena13/react-hotkeys#147]
**Is your feature request related to a problem? Please describe.**
We are trying to use the component prop to attach our hotkeys to a component, but we use functional components exclusively and the component prop only accepts a React.Component class component.

**Describe the solution you'd like**
Ability to use either Class Components or functional components as the `component` prop in the HotKeys component.

Is this already planned / are we missing a way to use functional components in the component prop?

**Comment by StephenHaney** [comment]
It's possible this is just a Type issue... in
https://github.com/greena13/react-hotkeys/blob/eb4163383a9680f52ca768ea32ba7e18f354bd90/index.d.ts#L61

It specifically says you must pass a Class component... can this type just be extended to accept functional components as well, or is this on purpose?

**Comment by greena13** [comment]
Hi @StephenHaney, thanks for reporting your issue.

This is likely indeed just a typing issue. I have not tested, but I believe a functional component should work just fine. The TypeScript definition file has always been a great source of issues in `react-hotkeys` (I don't use TypeScript directly, myself) and I end up leaning very heavily on the community to fix my mistakes/oversights.

I will have a go at updating the definition to include functional components and see if I can verify they do work as intended.

**Comment by greena13** [comment]
I have pushed a commit that I *think* should fix the TypeScript definitions. If you want to take a look, and perhaps make any suggestions or corrections it's available [here](https://github.com/greena13/react-hotkeys/commit/6ed8ead992f790765b5108a5d4a7dfcb3bf9c066).

It will go out with the next pre-release.
