### ISSUE TITLE
[FEATURE] Function add keycode for SmartTV

### ISSUE THREAD

**Issue by tconns** [greena13/react-hotkeys#156]
**Is your feature request related to a problem? Please describe.**
I'm working on a project on SmartTV using React-Hotkeys. Back key on webOS does not receive

**Describe the solution you'd like**
Add method to add KeyCode like mousetrap

**Describe alternatives you've considered**
Just open more self-defined uses of mouestrap as v1 version.

**Additional context**
The control keys on the remote have different codes. Example: webos: "461:" BackTV ", tizen:" 10009: "BackTV"

**Comment by greena13** [comment]
Hi @tconns, thanks for filing your issue.

I have no experience working with webOS, so you're going to have to help me out here. Could you please confirm you're referring to the [addKeycodes](https://craig.is/killing/mice#api.addKeycodes) method on mousetrap?

Could you also confirm in your examples that the KeyboardEvents have a `code` or `keyCode` of 461, and a `key` of "BackTV"?

**Comment by tconns** [comment]
Sorry for the late!

In v1, I used addKeycodes method on mousetrap, it works normally.
But in v2 version, addKeycode doesn't work, looks like mousetrap can't override listKeycode in library.

You can try the example of replacing the 'numlock' key name with the 'BackTV' key. Then call 'BackTV' to the handlers.

**Comment by tconns** [comment]
(Tizen) Mousetrap.addKeycodes({
      10009: "BackTV",
      10252: "PlayPauseTV",
      412: "PrevTV",
      415: "PlayTV",
      417: "NextTV",
      19: "PauseTV",
      413: "StopTV"
});
(WebOS)Mousetrap.addKeycodes({
      461: "BackTV",
      412: "PrevTV",
      415: "PlayTV",
      417: "NextTV",
      19: "PauseTV"
});
Can you add a method to add these keycode? Right now I am adding directly to the library's DictionaryKey but it still has some errors.

**Comment by greena13** [comment]
This feature is now available in [v2.0.0-pre8](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre8).
