### ISSUE TITLE
[FEATURE] Helper for transforming key presses into sequence strings

### ISSUE THREAD

**Issue by AndriySvyryd** [greena13/react-hotkeys#158]
This would be used to redefine hotkeys at runtime.

Something similar to https://github.com/ccampbell/mousetrap/tree/master/plugins/record

**Comment by greena13** [comment]
An interesting idea, @AndriySvyryd. 

This may be possible with a little modification.

**Comment by greena13** [comment]
If I am interpreting how that particular mousetrap plugin works correctly, I am not sure I like its approach. It appears that it simply waits for 1 second after the last key event before assuming that the user is done pressing keys, and setting the new key combination or sequence. I think I'd prefer a more explicit action, so as clicking a "Done" button (which would trigger a callback to tell `react-hotkeys` that the sequence should stop being recorded).

Would that work for your application, @AndriySvyryd?

**Comment by AndriySvyryd** [comment]
@greena13 For my application only a single key combination is needed at a time, so it would work best if it stopped recording on the last `keyup` (to allow for something like `ctrl+alt+shift+m` to be captured)

**Comment by greena13** [comment]
This feature is now available in [v2.0.0-pre8](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre8).
