### ISSUE TITLE
[BUG] How to prevent default execution of shortcut like ctrl+S?

### ISSUE THREAD

**Issue by ervishal89** [greena13/react-hotkeys#162]
**Describe the bug**
I am using hotkeys to capture a shortcut defined by user. when user pressed Ctrl+S, it open save as dialog. I want to prevent that. Could anyone help me how I can do that?

**How are you using react hotkeys components? 

HotKeys

**Expected behavior**
Ctrl+S should not open save dialog.
**Platform (please complete the following information):**
 - Version of react-hotkeys 1.3.0
 - Browser [e.g. chrome, safari] chroma
 - OS: [e.g. iOS] windows 10

**Are you willing and able to create a PR request to fix this issue?**

**APPLICABLE TO v2.0.0-pre1 AND ABOVE: ======================**

**Include the smallest log that includes your issue:**

Set logging to verbose (you'll need the development build if its possible):

```
import React, { Component } from 'react';
import Hotkeys from 'react-hot-keys';
import hotkeys1 from 'hotkeys-js';

export default class HotkeyDemo extends Component {
    constructor(props) {
        super(props);
        this.state = {
            output: 'Hello, I am a component',
        }
    }
    onKeyUp(keyNm, e, handle) {
        
    }
    onKeyDown(keyName, e, handle) {
        
        e.preventDefault()
        if(e.ctrlKey === true && e.keyCode === 83)
        {
            alert('pressed');
        }
        
        this.setState({ output: e.code })
    }
    render() {
        return (
            <Hotkeys
                keyName="*"
                onKeyDown={this.onKeyDown.bind(this)}
                onKeyUp={this.onKeyUp.bind(this)}
            >
                <div className="alexa-shortcut-key">
                    <input type="text" className="alexa-shortcut-textbox" readOnly value={this.state.output} />
                </div>
            </Hotkeys>
        )
    }
}
**What Configuration options are you using?**

```
configure({
  //options
})
```

**Comment by mrlubos** [comment]
@ervishal89 Have you tried `event.preventDefault()`? I can recommend this article on an excellent summary of [browser events](https://unixpapa.com/js/key.html).

**Comment by greena13** [comment]
Thanks for chipping in again, @mrlubos. I've added a [section](https://github.com/greena13/react-hotkeys#preventing-default-browser-behaviour) to the Readme to cover this in the future.
