### ISSUE TITLE
[BUG] TypeScript Error: Namespace 'React' has no exported member 'forwardRef'.

### ISSUE THREAD

**Issue by greena13** [greena13/react-hotkeys#164]
The following TypeScript error appears to be occurring:

```
node_modules/react-hotkeys/index.d.ts:84:15 - error TS2694: Namespace 'React' has no exported member 'forwardRef'.

84   ref?: React.forwardRef<React.ComponentClass, ComponentPropsBase>
```

**Comment by natew** [comment]
Ah, was curious if this was just me and see it's not. Will do a cursory look to see if I can fix.

**Comment by taromurao** [comment]
In React,

```
function forwardRef<T, P = {}>(Component: RefForwardingComponent<T, P>): ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>;
```

is not a type, but a function. What should be the type of `ref` in `react-hotkey`?

**Comment by taromurao** [comment]
Related:

This line's signature is also strange.

```
236  ignoreEventsCondition?: (KeyboardEvent) => boolean,
```

should be

```
236  ignoreEventsCondition?: (keyboardEvent: KeyboardEvent) => boolean,
```

?

**Comment by taromurao** [comment]
I noticed lately that b866ec15fafd91363ab4df3524e4cf892bc1b6a3 already fixed this problem. This issue should be closed.

**Comment by greena13** [comment]
Thanks for the heads-up (and PR), @taromurao!
