### ISSUE TITLE
[QUESTION] Default capture keys?

### ISSUE THREAD

**Issue by zeg-io** [greena13/react-hotkeys#165]
I would like to have a list of "cards" on a page be selectable simply by using the arrow keys (left/right). I have other pages where I have a text-box which makes capturing the keys simple and intuitive with this library (thank you).

So the idea would be you arrive at "Page" and there are a series of cards.  You tap the right arrow key and the first card highlights, tap again, the second, etc... hit enter, card is "clicked"

The main thing I don't get at the moment is how to have the focus travel with the card.  Meaning, if I press down it also scrolls my browser screen (not a behavior I want).  But, if I go down far enough the focus is on an card that I can no longer see, so I'm hoping someone here will know the best practice for handling such cases.

Again, thanks so much for this awesome library!

**Comment by greena13** [comment]
Hi @zeg-io,

I can point you in the direction of the (new) [Preventing default browser behaviour](https://github.com/greena13/react-hotkeys#preventing-default-browser-behaviour) section of the Readme, that you can use to stop the browser scrolling when you press the down key. I'd also recommend you check out the [Managing focus in the browser](https://github.com/greena13/react-hotkeys#managing-focus-in-the-browser) section, to ensure your cards can be programmatically focused. You may also want to check out [the scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method, to ensure the focused card is always visible - check if the browser support matches your target browsers.

Alternatively, it sounds like your use case is an ideal one for another library I have authored called [react-ref-manager](https://github.com/greena13/react-ref-manager). It is much less well known, and less mature/maintained than `react-hotkeys` - but it may be exactly what you need. I built  `react-ref-manager` to work well with `react-hotkeys` and use them together.

An example of using them together is as follows:

```javascript
import React, { Component } from 'react';
import { GlobalHotKeys } from 'react-hotkeys';

import RefManager, { FocusDirection } from 'react-ref-manager';

class MyComponent extends Component {
  constructor(props, context) {
    super(props, context);

    this.refManager = new RefManager(this);
  }

  render() {
    return (
      <GlobalHotKeys
        keyMap={ {
          FOCUS_RIGHT: 'right',
          FOCUS_LEFT: 'left',
          FOCUS_UP: 'up',
          FOCUS_DOWN: 'down',
        } }

        handlers={ {
          FOCUS_UP: () => this.focusNextCard(FocusDirection.UP),
          FOCUS_DOWN: () => this.focusNextCard(FocusDirection.DOWN),
          FOCUS_LEFT: () => this.focusNextCard(FocusDirection.LEFT),
          FOCUS_RIGHT: () => this.focusNextCard(FocusDirection.RIGHT),
        }}
      >
        { this.renderCards() }
      </GlobalHotKeys>
    );
  }

  renderCards() {
    const { cards } = this.props;

    cards.map((card) => (
      <div
        tabIndex={ -1 }
        key={card.id}
        ref={ (c) => this.refManager.set('cards', card.id, c) }
      >
        Title: { card.title }
      </div>
    ));
  }

  focusNextCard(direction) {
    const { cards }  = this.props;

    const firstCardRef = this.refManager.get('cards', cards[0].id);

    if (firstCardRef) {
      const collectionWidth =
        Math.floor(window.innerWidth / firstCardRef.getBoundingClientRect().width);

      const cardRefs = this.refManager.get('cards');

      this.refManager.focusNext(cardRefs, {
        direction,
        indexes: cards.map(({id}) => id),
        collectionWidth,
        xWrap: true,
      });
    }
  }
}

```
