### ISSUE TITLE
Set hotKey dynamically and get the sequence in handler

### ISSUE THREAD

**Issue by maxdonetsk** [greena13/react-hotkeys#169]
Hey @greena13, thanks a lot for this useful library!
I'm a newbie in it, so perhaps the feature I want to use is already exist.

I want to bind a sequence dynamically and fire a dynamic handler for it.
For instance:

```
const hotKeys = {
   openItem: ['ctrl 1 2 3', 'ctrl 1 2 4'] // I would like to use a dynamic array, so it could be ['1 2 3', '4 3 2', '9 5 3']
};

const handlers = {
  openItem:() => this.openItem(id); //how can I pass 123 or 124 as an id here?
};
```

I'll really appreciate your help!

**Comment by maxdonetsk** [comment]
Found. Maybe, it will be helpful for someone.
Since this library depends on Mousetrap, and according to its documentation:

```
Mousetrap.bind('ctrl+shift+up', function(e, combo) {
    console.log(combo); // logs 'ctrl+shift+up'
});
```

**Comment by greena13** [comment]
Hi @maxdonetsk,

Thanks for your question. This is an interesting use case - needing to have the key combination that was pressed available in the event handler. I had not considered such a requirement.

It is true that version 1.* is based on Mousetrap, however 2.* will not be and the above approach will not work.

I am open to passing the key combination to the event handler as an argument, as a new feature request, though.

**Comment by maxdonetsk** [comment]
@greena13 do you have any chance to leave this feature as is? It is sooo useful!
I'm going to implement a dynamic logic for hotkeys and handlers basing on this feature.
I guess, I'm not alone ;)
