### ISSUE TITLE
Delegate handlers to single Mousetrap binding

### ISSUE THREAD

**Issue by chrisui** [greena13/react-hotkeys#2]
`HotKeys` currently creates a Mousetrap instance for each component mounted. This could be optimized for the cases where you had _many_ hotkey targets (imagine hundreds of node's you had a 'delete' hotkey for) by having a single instance where handlers were bound to.

**Comment by Chrisui** [comment]
Having a single `HotKeyManager` would also solve the issue seen [here](http://chrisui.github.io/react-hotkeys/). If a deep handler is triggered for a key sequence which is a subset of a root sequence (Eg. `up` in `up down left right`) then the root sequence would never fire!

**Comment by Chrisui** [comment]
Note with https://github.com/Chrisui/react-hotkeys/commit/98b65bc04f86fba0c5a2480edf93bec75b09d51a the propagation issue seen in the mentioned example is now fixed.

A single delegation point should still be written though for best performance moving forwards.

**Comment by chrisui** [comment]
Closing to be tracked in https://github.com/chrisui/react-hotkeys/issues/2

Might re-open if it drops from v1 scope.

**Comment by greena13** [comment]
Reopening to track separately.

**Comment by greena13** [comment]
Closing as soon to be no longer relevant, with the removal of Mousetrap in version 2.0.0
