### ISSUE TITLE
CodeClimate Maintainability Score of C

### ISSUE THREAD

**Issue by greena13** [greena13/react-hotkeys#200]
Code Climate gives `react-hotkeys` a maintainability score of C. 

Now that the scope and function of the library has become clearer, it's time to refactor into a more manageable architecture, while maintaining the same API.

**Comment by jordantomax** [comment]
I'm so happy to see this issue 😄 that yellow stings my eyes lol

**Comment by greena13** [comment]
:) Yes, it's a form of public shaming to help motivate. The refactor is going reasonably well so far - you shouldn't have to bear it for too much longer.
