### ISSUE TITLE
[BUG] Special single key sequence shortcut does not work

### ISSUE THREAD

**Issue by chipta** [greena13/react-hotkeys#211]
**Describe the bug**

Special single key sequence such as `?`, `~` does not work. Seems like it's being detected as `Shift+?` instead. 

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
HotKeys

**Expected behavior**

Special single key sequence should work without adding `Shift+?` to keymap.

**Platform (please complete the following information):**
 - Version of react-hotkeys: 2.0.0-pre9
 - Browser [e.g. chrome, safari]: Chrome 75.0.3770.142
 - OS: [e.g. iOS]: Linux

**Are you willing and able to create a PR request to fix this issue?**
Not sure which part of the codebase to look at or modify.

**APPLICABLE TO v2.0.0-pre1 AND ABOVE: ======================**

```
Key history: [
    {
        "keys": {
            "Shift": [
                [
                    1,
                    0,
                    0
                ],
                [
                    1,
                    0,
                    1
                ]
            ],
            "~": [
                [
                    1,
                    1,
                    0
                ],
                [
                    1,
                    1,
                    1
                ]
            ]
        },
        "ids": [
            "Shift+~",
            "Shift+`",
            "#+Shift"
        ],
        "keyAliases": {
            "`": "~",
            "#": "~"
        }
    }
].
```

**What Configuration options are you using?**
Default configuration.

**Comment by greena13** [comment]
Hi @chipta, thanks for filing this problem.

You have provided extra context for a compromise the library is finding itself having to make between "honouring submatches" or not. Long story short: by default `react-hotkeys` doesn't observe submatches. 

However, you can make it with the following configuration option:

```
import { configure } from 'react-hotkeys';

configure({
  allowCombinationSubmatches: true
});
```

Please see [How combinations and sequences are matched](https://github.com/greena13/react-hotkeys#how-combinations-and-sequences-are-matched) for an explanation of the full implications of turning this option on.

**Comment by greena13** [comment]
I'm closing this issue for now, but feel free to let me know if you consider it still unresolved in any fashion.

**Comment by chipta** [comment]
Thanks @greena13! It works :+1:
