### ISSUE TITLE
Do I have to use allowChanges if my handlers need access to props which can change?

### ISSUE THREAD

**Issue by ZYinMD** [greena13/react-hotkeys#212]
I have handlers that involve props, something like this:

```js
const handlers = {
  FOO: () => {
    myFunc(someProp);
  }
};

return (
  <HotKeys handlers={handlers} keyMap={keyMap} allowChanges>
    {children}
  </HotKeys>
)
```

My question is, is there a way around using `allowChanges`?

In v1.x.x, I didn't have the `allowChanges`, then I upgraded to v2.0.0 and found my handlers broke because they don't use the newest prop, so I added `allowChanges`. But I think my case should be a very common case, is there a better way? I tried wrapping the `myFunc(someProp)` part in a separate function outside of handlers and call it inside the handler without supplying any arguments, but it didn't work.

**Comment by greena13** [comment]
Hi @ZYinMD, thanks for asking.

`react-hotkeys` v2 was designed to be "optimized by default". Part of this is not updating `handlers` or `keyMap` after a component mounts (`<GlobalHotKeys>`) or is (re)focused (`<HotKeys>`), unless the consumer of the library explicitly opts into honouring the updates. This is among the greatest measures taken to ensure `react-hotkeys` is as performant as possible.

If I am understanding you correctly, it sounds like your `keyMap` and `handlers` aren't changing - just the that your `handlers` are defined with references to the prop values as they exist at the time the component is mounted. 

I believe you can get around this by having your handlers that depend on props or state being methods on your component, that you reference. For example:

```
class MyComponent extends Component {
  constructor(props, context) {
     super(props, context);

    this.handleAction = this.handleAction.bind(this);
  }

  render() {
    const handlers = {
      ACTION: this.handleAction
    };

    const keyMap = {
      ACTION: 'a'
    };

    return (
      <HotKeys keyMap={keyMap} handlers={handlers} >
        // ...
      </HotKeys>
    );
  }

  handleAction() {
    // reference props or state here
   }
}
```

If you are using a function component, this may be trickier, and I suggest you just use the `allowChanges` prop.

Finally, if you want the v1 behaviour, you can enable it globally:

```
import { configure } from 'react-hotkeys';

configure({
  ignoreKeymapAndHandlerChangesByDefault: false
});
```

I wouldn't recommend this, but try it and see if you experience problems with performance. Small applications with few `<HotKeys>` components should be fine.

Hope this answers your question. I'm going to close the issue for now, to keep things moving forwards, but please feel free to reply if you need additional clarification.

**Comment by ZYinMD** [comment]
Hi @greena13, thanks so much for your explanation! Is v2 with `allowChanges` as performant as v1.x.x? In other words, was v1.x equally slow?

Using `allowChanges` doesn't bother me at all if it doesn't make the app slower than v1.x, but I noticed one thing became slower in my app after upgrading, and I wondered if `allowChanges` was the cause.

(Actually I think the new behavior is probably due to `SyntheticEvent` adoption, rather than a performance change, but I can't tell).

I'll use an exmaple to explain the change I observed, but my case must be a very specific edge case compared to the huge amount of scenarios react-hotkeys covers, so thanks so much for your time reading it.

Old component in v1.x:
```js
// a simplified example for demo purposes
function MyList({ dataArray, addItem }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
      focus('unique_id_0001');
    },
  };

  function focus(id) {
    let node = document.getElementById(id);
    if (node) node.focus();
  }

  return (
    <HotKeys handlers={handlers} keyMap={keyMap}>
      {dataArray.map(item => (
        <input id={item.id} value={item.title} key={item.id} />
      ))}
    </HotKeys>
  );
}
```

Changes needed in v2 to keep the same functionality:
```diff
function MyList({ dataArray, addItem }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
-      focus('unique_id_0001');
+      setTimeout(() => {
+        focus('unique_id_0001');
+      }, 0);
    },
  };

  function focus(id) {
    let node = document.getElementById(id);
    if (node) node.focus();
  }

  return (
-    <HotKeys handlers={handlers} keyMap={keyMap}>
+    <HotKeys handlers={handlers} keyMap={keyMap} allowChanges>
      {dataArray.map(item => (
        <input id={item.id} value={item.title} key={item.id} />
      ))}
    </HotKeys>
  );
}
```

In v1.x, I was able to synchronously find the new element showing up after the re-render, which I thought was magical, but it did work. In v2 I need to wait a tick, which produces a very noticeable delay (the re-render is fast, new item appears on the screen instantly, but the tick is surprisingly long. Since the focus has a color change, it's very noticeable - at least 200ms).

**Comment by ZYinMD** [comment]
Hi @greena13, thanks so much for your explanation! Is `v2 with allowChanges` as performant as v1.x? In other words, was v1.x equally slow?

Using `allowChanges` doesn't bother me at all if it's no slower than v1.x, but I noticed one thing became slower in my app after upgrading, and I wondered if `allowChanges` was the cause.

(Actually I think the new behavior is probably due to `SyntheticEvent` adoption, rather than a performance change, but I can't tell).

I'll use an exmaple to explain the change I observed, but my case must be a very specific edge case compared to the huge amount of scenarios react-hotkeys covers, so thanks so much for your time reading it.

Old component in v1.x:
```js
// a simplified example for demo purposes
function MyList({ dataArray, addItem }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
      focus('unique_id_0001');
    },
  };

  function focus(id) {
    let node = document.getElementById(id);
    if (node) node.focus();
  }

  return (
    <HotKeys handlers={handlers} keyMap={keyMap}>
      {dataArray.map(item => (
        <input id={item.id} value={item.title} key={item.id} />
      ))}
    </HotKeys>
  );
}
```

Changes needed in v2 to keep the same functionality:
```diff
function MyList({ dataArray, addItem }) {
  const keyMap = {
    NEW_ITEM: 'ctrl+n',
  };

  const handlers = {
    NEW_ITEM: () => {
      addItem('unique_id_0001'); // add a new element into dataArray, causing a re-render
-      focus('unique_id_0001');
+      setTimeout(() => {
+        focus('unique_id_0001');
+      }, 0);
    },
  };

  function focus(id) {
    let node = document.getElementById(id);
    if (node) node.focus();
  }

  return (
+    // need `allowChanges` because in parent level, `addItem` needs reference to `dataArray`
+    <HotKeys handlers={handlers} keyMap={keyMap} allowChanges>
-    <HotKeys handlers={handlers} keyMap={keyMap}>
      {dataArray.map(item => (
        <input id={item.id} value={item.title} key={item.id} />
      ))}
    </HotKeys>
  );
}
```

In v1.x, I was able to synchronously find the new element showing up after the re-render, which I thought was magical, but it did work. In v2 I need to wait a tick, which produces a very noticeable delay (the re-render is fast, new item appears on the screen instantly, but the tick is surprisingly long. Since the focus has a color change, it's very noticeable - at least 200ms).

**Comment by Slapbox** [comment]
@greena13 can you briefly explain why it is that defining handlers outside of `render()` fails?

```js
handlers = {
  //  ...
}

render() {
 const handlers = { 
  // ...
 }
 return (
   <GlobalHotKeys 
    handlers={handlers}  //  Works as expected
    // handlers={this.handlers}  // Nothing happens
    keyMap={keyMap} 
  />
  )
}
```
