### ISSUE TITLE
IgnoreGlobalKeys

### ISSUE THREAD

**Issue by johnli611** [greena13/react-hotkeys#222]
**Is your feature request related to a problem? Please describe.**
Yes, my problem is that some of the hotkeys in my app are available at the highest level of my app, but their handlers are defined much lower in the DOM (I'm using 3rd party libraries that must render in a descendent component). 

As a workaround, I'm using GlobalHotKeys instead of HotKeys. If I read correctly, the focused component has to be a descendent of the component that defines the handler (which is a leaf node).

Therefore, the actions don't fire in some parts of my app. They also don't fire if that component  where the handler is defined unmounts. When I use GlobalHotKeys, they always fire when I type in an input.

**Describe the solution you'd like**
I'm assuming it's too big of an ask to have a focused element look through its children for handlers, so instead I'd love a component that's similar to IgnoreKeys but can ignore GlobalHotKeys instead of just HotKeys. 

Maintaining focus programmatically is messy and frustrating when so many of my hotkeys are available to my users everywhere in the app. Please let me know if this is currently possible and I misread the docs.

**Describe alternatives you've considered**

I'm using global hot keys right now to bypass these behaviors, however it seems like there's no way to ignore them. They're always firing when I'm typing in an input and I'm pulling my hair out figuring out how to get it to work since IgnoreKeys don't ignore them.

**Comment by linusthe3rd** [comment]
@johnli611 Did you ever determine a workaround for this? I am experiencing the same issue now.

**Comment by damnitrahul** [comment]
@johnli611 Did you find a workaround for this?
