### ISSUE TITLE
What are Hard Sequences?

### ISSUE THREAD

**Issue by Slapbox** [greena13/react-hotkeys#235]
https://github.com/greena13/react-hotkeys/releases mentions "Hard Sequences". I wasn't clear from the description there what that means, and the link in that section of the Release Notes is dead.

**Comment by greena13** [comment]
Hi @Slapbox, you can read about the now removed feature "Hard Sequences" [here](https://github.com/greena13/react-hotkeys/tree/v2.0.0-pre2#deprecated-hard-sequence-handlers).
