### ISSUE TITLE
Is custom modifier key possible? For instance ` + 1

### ISSUE THREAD

**Issue by ZYinMD** [greena13/react-hotkeys#250]
Can I use custom modifier keys other than `ctrl`, `alt`, `shift`, etc? For instnace, I'd like to define a hotkey `` ` `` + `1`, is it possible?

Thanks!

**Comment by greena13** [comment]
@ZYinMD,

Going from memory, I believe this should be possible just by defining a **`+1** hotkey. I have not attempted it, though, so you may find it doesn't work perfectly in all situations.

**Comment by ZYinMD** [comment]
From my test, it doesn't work in either v2 or v1.1.4. The mousetrap doc also didn't mention anything about custom modifiers.

 It makes sense that it won't just work, because once you have a hotkey like `` ` ``+`1`, you need to think about what happens when you just press `` ` ``. The usual way of handling it by some other software is to do nothing but wait until key up, if `` ` `` was pressed and released without other keys, then fire `` ` `` on key up. But since you don't remember writing this mechanism I doubt it's there.

**Comment by greena13** [comment]
Curious. Would you happen to have the [(verbose) logs](https://github.com/greena13/react-hotkeys#logging) available for when you tried to trigger this keymap?

**Comment by ZYinMD** [comment]
Hi, I tried again, it does work. The only issue is if it happens inside an `input` or `textarea`, special handling is required to prevent `` ` `` from being typed out, and also if user does need to type `` ` `` out, they should be able to do it by press and then release the `` ` `` key. 

Anyway, it's solvable, thanks for you help! Closing.
