### ISSUE TITLE
[Question] Is this possible to be used with Chrome Extensions?

### ISSUE THREAD

**Issue by Spiderixius** [greena13/react-hotkeys#257]
Heya

I have a chrome extension that has shortcuts which I would like to activate while the user is typing. How likely is this package able to accomplish that? 

Regards
Admir

**Comment by greena13** [comment]
Hi @Spiderixius,

I have not attempted or designed this package to be used in a Chrome extension. I would suggest it's probably not the best tool for that particular job.
