### ISSUE TITLE
GlobalHotKeys not working when focused on the input field.

### ISSUE THREAD

**Issue by Gajesh-LH** [greena13/react-hotkeys#274]
**Describe the bug**
GlobalHotKeys not working when focused on the input field.

Demo (Recorded Screen Link): https://recordit.co/ffVKvn9uVw

**How are you using react hotkeys components? (HotKeys, GlobalHotKeys, IgnoreKeys etc)**
```
<GlobalHotKeys keyMap={REGISTRATION_KEY_MAP} handlers={this.handlers}>
      <RegistrationForm
         ref={regFormRef}
         onBillClick={this.onBillClick}
         patientId={this.state.patientID}
         openBill={this.state.openBill}
     />
</GlobalHotKeys>

    const handlers = {
        REGISTER: () => console.log(regFormRef),
        REGISTER_AND_BILL:  () => console.log(regFormRef),
    };

  const REGISTRATION_KEY_MAP = {
    REGISTER: ['command+enter', 'ctrl+enter'],
    REGISTER_AND_BILL: ['enter'],
  };
```
**Expected behavior**

If I am using <GlobalHotKeys> then it should directly fire the related action, the focus should not matter. Eg. I want to submit a form but currently, document focused on any input box then it should submit the form 

**Platform (please complete the following information):**
 - Version of react-hotkeys: `react-hotkeys v2.0.0`
 - Browser chrome
 - OS:  iOS v10.13.6

**Are you willing and able to create a PR request to fix this issue?**
- No

**Include the smallest log that includes your issue:**
   - https://recordit.co/ffVKvn9uVw

**What Configuration options are you using?**
- NO

**Comment by Gajesh-LH** [comment]
```
configure({
    ignoreTags: ['input', 'select', 'textarea'],
    ignoreEventsCondition: function() {}
});
```

Using this config. we can solve this issue.

**Comment by upender7270** [comment]
> ```
> configure({
>     ignoreTags: ['input', 'select', 'textarea'],
>     ignoreEventsCondition: function() {}
> });
> ```
> 
> Using this config. we can solve this issue.

I used this code but still not working when input in focus.  Anything changed here?
this I what is given,
```
ignoreTags: [],
ignoreEventsCondition: function () {
  return false
}
 ```
returned false as it is throwing tyescript error
