### ISSUE TITLE
Expose customHotKeys

### ISSUE THREAD

**Issue by framerate** [greena13/react-hotkeys#48]
I'm using this library on a smart TV platform and some of the keycodes don't seem to exist in Mousetrap. Mousetrap has support for this but it's not exposed to react-hotkeys

What I tried to do:

Add a customKeyCodes prop
```
propTypes: {
    children: React.PropTypes.node,
    onFocus: React.PropTypes.func,
    onBlur: React.PropTypes.func,
    keyMap: React.PropTypes.object,
    handlers: React.PropTypes.object,
    focused: React.PropTypes.bool, // externally controlled focus
    attach: React.PropTypes.any, // dom element to listen for key events,
    customKeyCodes: React.ProptTypes.array // custom keycodes in the format {123, 'banana', 456, foobar}
  },
```

and this inside componentDidMount():
```
// add custom keycodes to Mousetrap
    if (this.props.customKeyCodes) {
      this.__mousetrap__.addKeycodes(this.props.customKeyCodes);
    }
```

HOWEVER it seems you're doing some clever abstractions. If you're available to point me in the right direction, I'd like to make this work!

**Comment by keiver** [comment]
I'm also researching this, when using ```react-hotkeys``` there is a global object for ```Mousetrap``` on window, would it be possible to add the key bindings with that object? I haven't had a chance to test it.

**Comment by framerate** [comment]
@keiver I gave up due to no response and wrote my own simple keymapper :/

**Comment by chrisui** [comment]
Sorry for the lack of response, lot's of other things going on.

I would expect the code in the first comment here to work (ie. calling `this.__mousetrap__.addKeyCodes()`). What was the issue when doing this?

@framerate

**Comment by chrisui** [comment]
Looks like this method was only added in the most recent version https://github.com/ccampbell/mousetrap/releases/tag/1.6.0 though our semver dep should cater for this.

It looks like it is actually a static method on `Mousetrap` which should be available globally as @keiver mentioned. ie. `__mousetrap__.addKeyCodes()` won't work but initialising `Mousetrap.addKeyCodes()` once somewhere should.

**Comment by chrisui** [comment]
NB. Hoping to transfer ownership of this project into my company so we can have an active team maintain it as day-to-day rather than being a neglected project on the side.

**Comment by chrisui** [comment]
Whoops click happy

**Comment by framerate** [comment]
@chrisui - Just seems like bad practice to be touching `__variable`s. I was hoping to add a clean prop but was just missing something within the flow.

**Comment by chrisui** [comment]
Going to expose `Mousetrap` as an import in the upcoming version so you can do the following in your app bootstrapping.

```
import {Mousetrap} from 'react-hotkeys';

Mousetrap.addKeycodes({
    144: 'numlock'
});
```

**Comment by greena13** [comment]
Although untested, I believe these sorts of custom keys should "just work" in [v2.0.0-pre1](https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0-pre1) when it's released, soon.
