### ISSUE TITLE
Allowing events to bubble

### ISSUE THREAD

**Issue by Aryk** [greena13/react-hotkeys#52]
> A single key sequence could be handled by "in focus" multiple components however in most use cases it does not make much sense for a parent to handle the same hotkey if a child has already dealt with it. For this reason hotkey events will not propagate beyond the component which handles them *by default*.

So how can we override this default?

**Comment by ruanyl** [comment]
@Aryk I had the same issue here. However, it is impossible to override this. `react-hotkeys` internally avoid to call the handler on a parent component if a child component has the same handler(key sequence) defined. 

Here I have a workaround [react-keyboard](https://github.com/ruanyl/react-keyboard) which is on top of `react-hotkeys` but without the `propagation magic`.

It's just a simple wrap of `mousetrap`, and follows the rule of event propagation of `mousetrap`. It works fine in my project so far. Maybe you could take a look.

**Comment by Aryk** [comment]
Thanks for the suggestion, will have a look!
