### ISSUE TITLE
Implement HOC for react-hotkeys? 

### ISSUE THREAD

**Issue by vivian-eb** [greena13/react-hotkeys#63]
This library has been tremendously helpful in implementing key-related events. And a HotKeys HOC would make the application of the functionalities more standardized and decoupled as opposed to manually wrapped each component (that needs keyboard actions) with the HotKeys tag in the component file. 

I'd like to propose the following API: 

```
const withKeyboardNavigation = (Component, keyMap) => (
    class WithKeyboardNavigationWrapper extends PureComponent {
			...
			
            _getBoundHandlers() {
	            // returns bounded handlers
	        }
			...

            render () {
                // returns HOC-wrapped Component with keyMap & handlers props on the <HotKeys> tag, and a11y props on the <wrappedComponent> tag. 
	            
```

The keyboard action and the keyboard event are states on the HOC, and are passed in as props to the wrappedComponent. The component can then implement the appropriate methods according to the given props. 

Thoughts?

**Comment by albybarber** [comment]
I think this is a great idea! +1
