### ISSUE TITLE
How can i listen to keypress + click events?

### ISSUE THREAD

**Issue by borisyordanov** [greena13/react-hotkeys#79]
I want to be able to handle events like `ctrl + leftMouseclick`, how can i do that with react-hotkeys?

**Comment by brusherru** [comment]
@borisyordanov, You don't need this package, cause click event already contains modifiers like `ctrl`, `shift`, `alt`.

```
onClick(event) {
  console.log('ctrl', event.ctrlKey);
  console.log('meta', event.metaKey);
  console.log('shift', event.shiftKey);
}
```

**Comment by borisyordanov** [comment]
@brusherru I did need it for other shortcuts i needed to implement, but the click combo was handled in the way you suggested. Thanks for answering.
