### ISSUE TITLE
Correct repo link

### ISSUE THREAD

**Issue by jbmoelker** [greena13/react-hotkeys#80]
The link at the top of the repository currently links to https://chrisui.github.io/react-hotkeys, which no longer works.

<img width="784" alt="screen shot 2018-01-22 at 07 56 32" src="https://user-images.githubusercontent.com/1516059/35208710-f55b0e96-ff49-11e7-8d30-daeb38ff0a40.png">

It should be https://greena13.github.io/react-hotkeys/

**Comment by greena13** [comment]
Thanks for letting me know, jbmoelker.
