### ISSUE TITLE
Using complicated hotkeys (ctrl+shift+e+n+g) doesnt work properly

### ISSUE THREAD

**Issue by reetou** [greena13/react-hotkeys#81]
React-hotkeys version: 0.10.0
React version: 15.4.2
We're also using electron v1.7.9. 
Using hotkeys such I mentioned (ctrl+shift+e+n+g) provides unexpected(imo) behavior. With working ctrl+shift+e+n+g combination there are also a hotkey that triggers via ctrl + shift + g, after some tries I finally figured out that in combinations like mine with characters as members of a hotkey using special keys + last character key also triggers that hotkey. 
Use this hotkey to reproduce: `"ctrl+shift+e+n+g"` and then press ctrl + shift + g

**Comment by greena13** [comment]
Hello, @reetou. Let me see if I understand you correctly:

* You have a hotkey action attached to the key combination `ctrl+shift+e+n+g` (ctrl, then shift, then 'e', then 'n', then 'g')
* You also have a hotkey action attached to the key combination `ctrl+shift+g` (ctrl, then shift, then 'g')
* When you press the key sequence to call handlers attached to the first action (`ctrl+shift+e+n+g`), the handlers for the second action are *also* called (`ctrl+shift+g`).

If that's correct, can you tell me:

* Which handler gets called first? 
* What arrangement and nesting of `HotKeys` components are you using? (which `HotKeys` defines each of the actions and which one defines each of the handlers?)

**Comment by greena13** [comment]
Closing this for now as it doesn't seem to be moving and I am still unclear about the specific test case to reproduce and resolve this issue. Please comment if you are interested in continuing this and I'll try and help out as best I can.
