### ISSUE TITLE
Typescript error finding declaration for FocusTrap

### ISSUE THREAD

**Issue by lehresman** [greena13/react-hotkeys#89]
I have `noImplicityAny` enabled in my `tsconfig.json`.  When I try to add react-hotkeys to my project, Typescript is giving this error:

TS7016: Could not find a declaration file for module './cjs/FocusTrap'. '{snip}/node_modules/react-hotkeys/cjs/FocusTrap.js' implicitly has an 'any' type.

Typescript version 2.7.2
Latest react-hotkeys from NPM

**Comment by greena13** [comment]
Thanks for reporting, @lehresman. The addition more strict typings to this package has certainly been a learning experience.
