### ISSUE TITLE
Hash/pound/hashtag/# key on Mac

### ISSUE THREAD

**Issue by gpmcadam** [greena13/react-hotkeys#93]
If you try to bound on `#` (hash/hashtag/pound key), this will work on keyboards that have a key for that, but on Mac keyboard layout, this is a key shortcut (`Option-3` in the EN-GB Mac layout, different for other regions, I suspect.)

How should this be handled within react-hotkeys, as right now, just binding on `#` doesn't work on Mac when I het `Option-3`.

**Comment by greena13** [comment]
Hey @gpmcadam, I am not sure as I don't have access to that particular keyboard layout.

I believe you should be able to manually bind a listener to a UI element and inspect the name of the singular key or key combination that occurs [using onkeypress](https://www.w3schools.com/jsref/event_onkeypress.asp).

I believe you will need to do this *outside of React* (as React provides its own synthetic key events) to get a true representation of what Mousetrap (the key matcher currently used internally by react-hotkeys) sees.

So:
1. In a React component's render method, assign any old component a `ref`
2. In the `componentDidMount` method of that component, assign a `onkeypress` handler to the element pointed to by that ref that logs out the event(s)
3. Open the browser, click on the corresponding element or one of its children, press your key and see what's logged in the console.

We'll go from there.

**Comment by greena13** [comment]
I'm going to close this issue for now. Please comment if you are interested in picking this thread up again and I'll try and support you how I can.
