### ISSUE TITLE
TypeScript 2.8.1 definitions error

### ISSUE THREAD

**Issue by crsanti** [greena13/react-hotkeys#99]
Hi, first of all, thanks for this awesome lib!

I'm currently having some issues with typings:

```
TS1254: A 'const' initializer in an ambient context must be a string or numeric literal.
```

Caused by:

```ts
export const withHotKeys = (keyMap: { [key: string]: KeySequence }) => HotKeys;
```

The issue is gone if I replace function expression with function declaration:

```ts
export declare function withHotKeys(keyMap: { [key: string]: KeySequence }): HotKeys;
```

**Comment by greena13** [comment]
Hey @crsanti, thanks for reporting this.

TypeScript has proven to not be my strong suite recently. I don't use it directly (only as a form of static markup through my IDE), so unfortunately I rely on those who do to raise issues.

I've had a quick read around your suggestion and it indeed does seem to be the correct way declare a function in this case. I'll make the change and deploy it with the next release.
